### ISSUE TITLE
Do not close music tab, no matter what

### ISSUE THREAD

**Issue by vilie** [ccampbell/xtab#1]
Music tab should not be closed no matter what.

Even though in newer versions of chrome you can see a speaker icon near the tab that is making music i couldn't find any call to check this behavior per tab. Maybe we can take the decision based on the links (don't close pandora/youtube links?)

**Comment by gianpaj** [comment]
Just whitelist certain tabs. Are pinned tabs excluded already?

**Comment by ccampbell** [comment]
Yes, pinned tabs are already excluded

**Comment by walles** [comment]
[The Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg) has an option to "not suspend tabs that are playing audio", so this should be possible.

**Comment by walles** [comment]
Here's the official API for detecting audio playing tabs, look for `audible` on this page:
https://developer.chrome.com/extensions/tabs

This most likely did not exist at the time this issue was opened, but it does now!

**Comment by Pictor13** [comment]
Nice.

Maybe it would be better to check it just if the user specifies that one as desired behaviour?

**Comment by senpl** [comment]
By option is always nice, anyway most users do not want to make their music or movie closed, so by default it should be not closed when audio is playing.

**Comment by ccampbell** [comment]
This functionality has been added in version 1.0.0 of the extension. I am doing a slow rollout, but you can manually install it from the Chrome web store if you would like to try it.
