### ISSUE TITLE
How to download the old version of the Chrome extension?

### ISSUE THREAD

**Issue by gianpaj** [ccampbell/xtab#12]
The new one opens the tab and closes it only after a few seconds.

When I'm opening 3/4 links I now don't realise that which were not opened.

In the new version, there are no options - as far as I can see

**Comment by ccampbell** [comment]
Hi @gianpaj 

Can you please provide me with more info? What do you have the behavior set to? Is it to block new tabs from opening? If so, I changed the behavior to show a warning page, but the old behavior to block immediately is still there. Take a look at this example:

![xtabblock](https://user-images.githubusercontent.com/259316/55401378-89c0bb00-551e-11e9-808b-a3d3d275e89d.gif)

Hopefully that is what you are referring to. If not, please let me know!

**Comment by ccampbell** [comment]
Closing this. Please reopen if I misunderstood or there is still an issue.

**Comment by gianpaj** [comment]
Hi Craig,

Thanks for the gif in your reply. I got confused because the Options menu is greyed out when you press right-click so I thought there were no options at all.

![Screenshot 2019-04-03 at 22 23 112](https://user-images.githubusercontent.com/899175/55507044-897c0900-565f-11e9-8e41-aa663bb8307c.png)


Cheers

**Comment by ccampbell** [comment]
Ahhh. Yes. The options are in the popup itself. I can probably make it so selecting Options in the right click menu loads the popup code in a new tab. Sorry for the confusion!

I realize changing the default behavior is generally a bad idea. I went back and forth on it, and ultimately decided that the warning would be a better default, but I actually have no idea.

Glad you figured it out.
