### ISSUE TITLE
Display notification when blocking tab

### ISSUE THREAD

**Issue by ibnuh** [ccampbell/xtab#8]
I found it a little bit annoying when I tried to open a new link then its not opened, so I need to figure it out for a while then I remember I have xTab. 

Can you please consider to add an option to display a little notification when it blocking new tab. 

Thanks,
Ibnuh

**Comment by ccampbell** [comment]
This functionality has been added in version 1.0.0 of the extension. I am doing a slow rollout, but you can manually install it from the [Chrome web store](https://chrome.google.com/webstore/detail/xtab/amddgdnlkmohapieeekfknakgdnpbleb) if you would like to try it.

When you have it set to “Block new tabs” it will now show a warning page by default. I experimented with flashing the icon, but it was too subtle. Here is the current behavior (ignore the weird artifacts in this gif):

![xtabclose](https://user-images.githubusercontent.com/259316/55254871-6bfa0a00-522f-11e9-88cd-032d7c6ae9d0.gif)
